# Generated by Django 5.2.8 on 2025-11-30 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_permission_role_remove_employee_role_employeerole_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(related_name='roles', through='employees.RolePermission', to='employees.permission'),
        ),
    ]
