# Generated by Django 5.2.8 on 2026-03-11 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expenses', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_items', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='expensepayment',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='expenses.expenseitem'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['name'], name='expenses_su_name_620359_idx'),
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='expenses.supplier'),
        ),
        migrations.AddIndex(
            model_name='expensepayment',
            index=models.Index(fields=['expense'], name='expenses_ex_expense_8804ae_idx'),
        ),
        migrations.AddIndex(
            model_name='expensepayment',
            index=models.Index(fields=['paid_at'], name='expenses_ex_paid_at_c5f5e3_idx'),
        ),
        migrations.AddConstraint(
            model_name='expensepayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_amount_gt_zero'),
        ),
        migrations.AddIndex(
            model_name='expenseitem',
            index=models.Index(fields=['supplier'], name='expenses_ex_supplie_c4bbe8_idx'),
        ),
        migrations.AddIndex(
            model_name='expenseitem',
            index=models.Index(fields=['product'], name='expenses_ex_product_6a9570_idx'),
        ),
        migrations.AddIndex(
            model_name='expenseitem',
            index=models.Index(fields=['created_at'], name='expenses_ex_created_e6b217_idx'),
        ),
        migrations.AddIndex(
            model_name='expenseitem',
            index=models.Index(fields=['payment_group_id'], name='expenses_ex_payment_1d3367_idx'),
        ),
        migrations.AddConstraint(
            model_name='expenseitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='expense_quantity_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='expenseitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gt', 0)), name='expense_unit_price_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='expenseitem',
            constraint=models.CheckConstraint(condition=models.Q(('total_price__gte', 0)), name='expense_total_price_non_negative'),
        ),
    ]
