# Generated by Django 5.2.8 on 2026-07-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_harden_pin_storage'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('schema_name', models.CharField(max_length=63)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
