# Generated by Django 5.2.8 on 2026-03-20 11:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_year', models.IntegerField()),
                ('period_month', models.IntegerField()),
                ('base_monthly', models.DecimalField(decimal_places=2, help_text='Snapshot of contract base salary at generation time.', max_digits=12)),
                ('working_days', models.IntegerField(help_text='Total expected working days in the period.')),
                ('days_present', models.DecimalField(decimal_places=2, help_text='Weighted attendance days (PRESENT=1, HALF_DAY=0.5, LATE=1).', max_digits=6)),
                ('days_on_leave', models.DecimalField(decimal_places=2, default=0, help_text='Weighted leave days based on contract leave_pay_policy.', max_digits=6)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, help_text='Manual deductions — tax, advances, etc.', max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, default=0, help_text='net_amount - total_paid', max_digits=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('PARTIAL', 'Partial'), ('PAID', 'Paid')], default='DRAFT', max_length=10)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_salaries', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_year', '-period_month', 'employee__name'],
            },
        ),
        migrations.CreateModel(
            name='SalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('MPESA', 'M-Pesa')], max_length=15)),
                ('reference', models.CharField(blank=True, help_text='Transaction ref, cheque number, M-Pesa code, etc.', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('paid_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_payments_made', to=settings.AUTH_USER_MODEL)),
                ('salary_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='hr.salaryrecord')),
            ],
            options={
                'ordering': ['-paid_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_in', models.TimeField(blank=True, help_text='Null for ABSENT records.', null=True)),
                ('time_out', models.TimeField(blank=True, help_text='Null until employee checks out.', null=True)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late'), ('HALF_DAY', 'Half Day')], default='PRESENT', max_length=10)),
                ('source', models.CharField(choices=[('SELF', 'Self'), ('MANAGER', 'Manager')], default='SELF', max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(blank=True, help_text='Null if source=SELF.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_attendance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'employee__name'],
                'indexes': [models.Index(fields=['employee', 'date'], name='hr_attendan_employe_0dcc0e_idx'), models.Index(fields=['date'], name='hr_attendan_date_07a719_idx'), models.Index(fields=['status'], name='hr_attendan_status_3539b0_idx')],
                'unique_together': {('employee', 'date')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=150)),
                ('position', models.CharField(max_length=150)),
                ('employment_type', models.CharField(choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('CONTRACT', 'Contract')], default='FULL_TIME', max_length=20)),
                ('date_hired', models.DateField()),
                ('base_monthly', models.DecimalField(decimal_places=2, max_digits=12)),
                ('check_in_time', models.TimeField(default='09:00', help_text='Official start time. Arrivals after this + grace period are LATE.')),
                ('late_threshold_mins', models.IntegerField(default=15, help_text='Grace period in minutes before marking as LATE.')),
                ('working_days_per_week', models.IntegerField(default=5, help_text='Used to calculate expected working days per month.')),
                ('leave_pay_policy', models.CharField(choices=[('FULL_PAY', 'Full Pay'), ('HALF_PAY', 'Half Pay'), ('NO_PAY', 'No Pay')], default='FULL_PAY', help_text='How approved leave days count toward salary. FULL_PAY=1.0, HALF_PAY=0.5, NO_PAY=0.0', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['employee__name'],
                'indexes': [models.Index(fields=['department'], name='hr_employee_departm_ffabac_idx'), models.Index(fields=['is_active'], name='hr_employee_is_acti_913125_idx')],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('SICK', 'Sick Leave'), ('ANNUAL', 'Annual Leave'), ('UNPAID', 'Unpaid Leave'), ('MATERNITY', 'Maternity Leave'), ('PATERNITY', 'Paternity Leave')], max_length=15)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_leaves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['employee', 'status'], name='hr_leavereq_employe_1b7929_idx'), models.Index(fields=['start_date', 'end_date'], name='hr_leavereq_start_d_9e9e54_idx'), models.Index(fields=['status'], name='hr_leavereq_status_694c52_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='salaryrecord',
            index=models.Index(fields=['employee', 'period_year', 'period_month'], name='hr_salaryre_employe_1544db_idx'),
        ),
        migrations.AddIndex(
            model_name='salaryrecord',
            index=models.Index(fields=['status'], name='hr_salaryre_status_7e04aa_idx'),
        ),
        migrations.AddIndex(
            model_name='salaryrecord',
            index=models.Index(fields=['period_year', 'period_month'], name='hr_salaryre_period__fdb83a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='salaryrecord',
            unique_together={('employee', 'period_year', 'period_month')},
        ),
        migrations.AddIndex(
            model_name='salarypayment',
            index=models.Index(fields=['salary_record'], name='hr_salarypa_salary__6498d1_idx'),
        ),
        migrations.AddIndex(
            model_name='salarypayment',
            index=models.Index(fields=['paid_at'], name='hr_salarypa_paid_at_d03743_idx'),
        ),
    ]
