# Generated by Django 5.2.8 on 2025-12-08 15:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
                ('unit', models.CharField(default='kg', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('movement_type', models.CharField(choices=[('IN', 'Incoming'), ('OUT', 'Outgoing')], max_length=10)),
                ('reason', models.CharField(choices=[('PURCHASE', 'Purchase'), ('RETURN', 'Return'), ('ADJUSTMENT', 'Adjustment'), ('SALE', 'Sale'), ('COOKING', 'Cooking'), ('DAMAGED', 'Damaged'), ('LOST', 'Lost')], max_length=20)),
                ('group_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expense_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='expenses.expenseitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.product')),
            ],
        ),
    ]
