# Generated by Django 5.2.8 on 2026-03-11 10:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('POS', '0001_initial'),
        ('expenses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
                ('unit', models.CharField(default='kg', max_length=50)),
                ('auto_deduct_on_sale', models.BooleanField(default=True, help_text='If True, POS sales automatically create OUT stock movements. If False, sales do not affect inventory automatically.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='inventory_p_name_f6a6a1_idx'), models.Index(fields=['category'], name='inventory_p_categor_b457a1_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Always positive. Direction via movement_type.', max_digits=12)),
                ('movement_type', models.CharField(choices=[('IN', 'Incoming'), ('OUT', 'Outgoing')], max_length=10)),
                ('reason', models.CharField(choices=[('PURCHASE', 'Purchase'), ('RETURN', 'Return'), ('ADJUSTMENT', 'Adjustment'), ('SALE', 'Sale'), ('COOKING', 'Cooking'), ('DAMAGED', 'Damaged'), ('LOST', 'Lost')], max_length=20)),
                ('funded_by_business', models.BooleanField(default=True, help_text='False if stock was acquired using personal/outside cash')),
                ('group_id', models.CharField(blank=True, max_length=100, null=True)),
                ('order_item_id', models.BigIntegerField(blank=True, help_text='OrderItem ID that caused this movement (POS audit)', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expense_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='expenses.expenseitem')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.product')),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='POS.receipt')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', 'movement_type'], name='inventory_s_product_5cb5b6_idx'), models.Index(fields=['reason'], name='inventory_s_reason_03e330_idx'), models.Index(fields=['created_at'], name='inventory_s_created_05ebf5_idx'), models.Index(fields=['group_id'], name='inventory_s_group_i_730910_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counted_quantity', models.FloatField(help_text='Physically counted stock')),
                ('system_quantity', models.FloatField(help_text='System-calculated stock at time of count')),
                ('difference', models.FloatField(help_text='counted_quantity - system_quantity')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('counted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reconciliations', to=settings.AUTH_USER_MODEL)),
                ('counted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_counts', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliations', to='inventory.product')),
            ],
            options={
                'ordering': ['-counted_at'],
                'indexes': [models.Index(fields=['product', 'status'], name='inventory_s_product_c6262c_idx'), models.Index(fields=['counted_at'], name='inventory_s_counted_74d094_idx')],
            },
        ),
    ]
