# Generated by Django 5.2.8 on 2026-02-05 14:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0001_initial'),
        ('expenses', '0002_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counted_quantity', models.FloatField(help_text='Physically counted stock')),
                ('system_quantity', models.FloatField(help_text='System-calculated stock at time of count')),
                ('difference', models.FloatField(help_text='counted_quantity - system_quantity')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('counted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-counted_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='product',
            name='auto_deduct_on_sale',
            field=models.BooleanField(default=True, help_text='If True, POS sales automatically create OUT stock movements. If False, sales do not affect inventory automatically.'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='funded_by_business',
            field=models.BooleanField(default=True, help_text='False if stock was acquired using personal/outside cash'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='order_item_id',
            field=models.BigIntegerField(blank=True, help_text='OrderItem ID that caused this movement (POS audit)', null=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='POS.receipt'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity',
            field=models.DecimalField(decimal_places=3, help_text='Always positive. Direction via movement_type.', max_digits=12),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='inventory_p_name_f6a6a1_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='inventory_p_categor_b457a1_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['product', 'movement_type'], name='inventory_s_product_5cb5b6_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['reason'], name='inventory_s_reason_03e330_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['created_at'], name='inventory_s_created_05ebf5_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['group_id'], name='inventory_s_group_i_730910_idx'),
        ),
        migrations.AddField(
            model_name='stockreconciliation',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reconciliations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockreconciliation',
            name='counted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_counts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockreconciliation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliations', to='inventory.product'),
        ),
        migrations.AddIndex(
            model_name='stockreconciliation',
            index=models.Index(fields=['product', 'status'], name='inventory_s_product_c6262c_idx'),
        ),
        migrations.AddIndex(
            model_name='stockreconciliation',
            index=models.Index(fields=['counted_at'], name='inventory_s_counted_74d094_idx'),
        ),
    ]
