# Generated by Django 5.2.8 on 2026-03-16 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='auto_deduct_on_sale',
            field=models.BooleanField(default=False, help_text='If True, POS sales automatically create OUT stock movements. Set True only for products sold directly through the POS counter. Leave False for raw ingredients, cooking supplies, etc.'),
        ),
    ]
