# Generated by Django 5.2.8 on 2026-05-09 01:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('POS', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='creditaccount',
            name='approved_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approved_credits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditaccount',
            name='settled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settled_credits', to=settings.AUTH_USER_MODEL),
        ),
    ]
