# Generated by Django 5.2.8 on 2026-06-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('drinks', 'Drinks'), ('snacks', 'Snacks'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
