# Generated by Django 5.2.8 on 2026-03-16 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0004_creditaccount_settled_at_creditaccount_settled_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='menu_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='POS.menuitem'),
        ),
        migrations.AlterField(
            model_name='posstockmovement',
            name='deducted_from_inventory',
            field=models.BooleanField(default=False),
        ),
    ]
